DROP TABLE IF EXISTS Books;
DROP TABLE IF EXISTS Person;

CREATE TABLE IF NOT EXISTS  Person  (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio varchar NOT NULL UNIQUE,
    birth_year int CHECK (birth_year > 1900)
);

CREATE TABLE IF NOT EXISTS  Books  (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    name varchar NOT NULL,
    author varchar NOT NULL,
    year int,
    date_of_taking date DEFAULT CURRENT_DATE
);

INSERT INTO Person(fio, birth_year) VALUES ('Иванов Иван Иванович', 1970);
INSERT INTO Person(fio, birth_year) VALUES ('Петров Петр Петрович', 1960);
INSERT INTO Person(fio, birth_year) VALUES ('Алексеев Алексей Алексеевич', 1989);
INSERT INTO Person(fio, birth_year) VALUES ('Познер Владимир Владимирович', 1944);
INSERT INTO Person(fio, birth_year) VALUES ('Федоров Мирон Янович', 1985);


INSERT INTO Books(person_id, name, author, year) VALUES (null,'Над пропостью во ржи', 'Джером Сэлинджер', 1951);
INSERT INTO Books(person_id, name, author, year) VALUES (null,'День опричника', 'Владимир Сорокин', 2006);
INSERT INTO Books(person_id, name, author, year) VALUES (null,'Тайные виды на гору Фудзи', 'Владимир Пелевин', 2018);
INSERT INTO Books(person_id, name, author, year) VALUES (null,'Философия Java', 'Брюс Эккель', 2018);
INSERT INTO Books(person_id, name, author, year) VALUES (null,'Психопотология обыденной жизни', 'Фрейд Зигмунд', 1904);
INSERT INTO Books(person_id, name, author, year) VALUES (null,'Игра в бисер', 'Герман Гессе', 1943);
INSERT INTO Books(person_id, name, author, year) VALUES (null,'Бытие и время', 'Мартин Хайдеггер', 1927);

UPDATE Books SET person_id=1 WHERE id=1;
UPDATE Books SET date_of_taking='2023-03-18' WHERE id=1;
UPDATE Books SET person_id=1 WHERE id=2;
UPDATE Books SET date_of_taking='2023-03-25' WHERE id=2;

--SELECT * FROM Person;
SELECT *FROM Books;